# Copyright (c) 2025, Your Company and contributors
# For license information, please see license.txt

import frappe
import pandas as pd
import os
import uuid
import json

class DataExportTools:
	"""
	Tools for exporting arbitrary SQL datasets generated by the AI
	into publicly accessible .csv files and returning the download link.
	"""
	
	@staticmethod
	def export_query_to_csv(query, user=None):
		"""
		Takes a safe SELECT query, executes it, converts it to a CSV file in the 
		public folder, and returns a download link to the user.
		"""
		try:
			# Verify query safety first (similar to nl_sql.py logic)
			query_upper = query.upper()
			dangerous_keywords = ['UPDATE', 'DELETE', 'DROP', 'INSERT', 'ALTER', 'TRUNCATE', 'GRANT', 'REVOKE']
			
			for keyword in dangerous_keywords:
				if keyword in query_upper:
					return {
						"message": f"Security Error: The query contains restricted keyword '{keyword}'. Only SELECT queries are permitted for data export.",
						"success": False
					}
			
			if not query_upper.strip().startswith('SELECT'):
				return {
					"message": "Only SELECT queries are evaluated during data export.",
					"success": False
				}
				
			# Execute Query
			data = frappe.db.sql(query, as_dict=True)
			if not data:
				return {
					"message": "The executed query returned no data to export.",
					"success": True
				}
				
			# Convert to Pandas DataFrame
			df = pd.DataFrame(data)
			
			# Generate Unique Filename
			filename = f"ai_export_{str(uuid.uuid4())[:8]}.csv"
			file_path = frappe.get_site_path('public', 'files', filename)
			
			# Save purely explicitly to site public files directory
			df.to_csv(file_path, index=False)
			
			download_link = f"/files/{filename}"
			
			html_response = f"""
			<div style='padding:15px; background-color:#ebf4ff; border-left:4px solid #3182ce; border-radius:4px;'>
				<strong>Data Export Successful!</strong><br><br>
				Your dataset has been processed and is ready for download.<br>
				Total Rows: {len(df)}<br><br>
				<a href='{download_link}' target='_blank' class='btn btn-primary btn-sm' style='text-decoration:none; color:white;'>Download CSV File</a>
			</div>
			"""
			
			return {
				"message": html_response,
				"success": True,
				"type": "text"
			}
			
		except Exception as e:
			frappe.log_error(frappe.get_traceback(), "ApexAiAssistant Data Export Error")
			return {"message": f"Failed to export data: {str(e)}", "success": False}
